<?php

namespace Pages\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * ColumnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColumnRepository extends EntityRepository
{
}
