Pages\Entities\Page:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
  oneToMany:
    children:
      targetEntity: Pages\Entities\Page
      mappedBy: parent
  manyToOne:
    parent:
      targetEntity: Pages\Entities\Page
      inversedBy: children